export const UPDATE_WORD_COUNT = "UPDATE_WORD_COUNT";
export const UPDATE_START_DISTANCE = "UPDATE_START_DISTANCE";
export const UPDATE_LETTERS_IN_WORDS = "UPDATE_LETTERS_IN_WORDS";
export const UPDATE_STEP_DISTANCE = "UPDATE_STEP_DISTANCE";
export const UPDATE_SPEED = "UPDATE_SPEED";
